# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/
#
#
app_identifier "kr.miin.Vinyler"
username "min.songkyung@gmail.com"

app_review_information(
  first_name: "Songkyung",
  last_name: "miin",
  phone_number: "+82 10 4591 4659",
  email_address: "min.songkyung@gmail.com",
)

copyright "#{Time.now.year} Songkyung Min"

primary_category 'MZGenre.Entertainment'

 release_notes({
  'default' => "Scan the barcode of the Vinyl! :)"
})
