# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :first_release do

  sync_code_signing(type: "appstore")

  produce(
      username: 'min.songkyung@gmail.com',
      app_identifier: 'kr.miin.Vinyler',
      app_name: 'Vinyler',
      language: 'Korean',
      app_version: '1.0')

  build_app(scheme: "Vinyler")

  deliver(
    submit_for_review: true,
    force: true,
    automatic_release: false,
    skip_binary_upload: true,
    metadata_path: "./metadata",
    app_version: "1.0",
    skip_app_version_update: false,
    skip_metadata: false,
    submission_information: {
      add_id_info_limits_tracking: true,
      add_id_info_serves_ads: true,
      add_id_info_tracks_action: true,
      add_id_info_tracks_install: true,
      add_id_info_uses_idfa: true,
      content_rights_has_rights: true,
      content_rights_contains_third_party_content: true,
      export_compliance_platform: 'ios',
      export_compliance_compliance_required: false,
      export_compliance_encryption_updated: false,
      export_compliance_app_type: nil,
      export_compliance_uses_encryption: false,
      export_compliance_is_exempt: false,
      export_compliance_contains_third_party_cryptography: false,
      export_compliance_contains_proprietary_cryptography: false, 
      export_compliance_available_on_french_store: false 
    }
)


end


  lane :tests do
  run_tests(workspace: "Vinyler.xcworkspace",
            devices: ["iPhone 6s", "iPhone XS Max"]
          )
  end

lane :release do
  build_app(scheme: "Vinyler",
            workspace: "Vinyler.xcworkspace",
            include_bitcode: true)
end




end
